---
- name: Removing repo existing folder
  file:
    path: "{{ node_app_location }}"
    state: absent

- name: Install Forever
  npm:
    name: forever
    global: yes
    state: present

- name: Check list of running Node.js apps.
  command: forever list
  register: forever_list
  changed_when: false

- name: Stop all forever instances
  command: forever stopall
