---
- name: Removing repo existing folder
  file:
    path: "{{ node_app_location }}"
    state: absent

- git:
    repo: 'https://github.com/stackbuilders/nano-chat.git'
    dest: "{{ node_app_location }}"

- name: Install Forever
  npm:
    name: forever
    global: yes
    state: present

- name: Install Sequelize CLI
  npm:
    name: sequelize-cli
    global: yes
    state: present

- name: Check list of running Node.js apps.
  command: forever list
  register: forever_list
  changed_when: false

- name: Stop all forever instances
  command: forever stopall

- name: Start example Node.js app.
  command: "make start -C {{ node_app_location }}"

- name: Run database migration
  command: sequelize db:migrate
  args:
    chdir: "{{ node_app_location }}/backend"

- name: Insert seed data
  command: sequelize db:seed:all
  args:
    chdir: "{{ node_app_location }}/backend"