---

- hosts: database
  become: true

  tasks:
    - name: Set a hostname
      hostname:
        name: "database"
 
    - name: add hostname to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost database'
        state: present

  roles:
    - role: geerlingguy.postgresql
      postgresql_databases:
        - name: nanochat
      postgresql_users:
        - name: admin
          password: admin
      tag: database

    - role: default-apps
      tag: apps
