---
- hosts: webserver
  become: true
  
  tasks: 
    - name: Set a hostname
      hostname:
        name: "webserver"

    - name: add hostname to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost webserver'
        state: present

  roles:
    - role: jdauphant.nginx
      nginx_http_params:
        - sendfile "on"
        - access_log "/var/log/nginx/access.log"
      nginx_sites:
        default:
         - listen 80
         - location / { proxy_pass http://localhost:3001; }
      notify:
      - restart nginx
     
    - role: geerlingguy.nodejs
      tag: nodejs
      nodejs_version: "8.x"
